#!/bin/bash
# setup_mac2.sh — Automated setup script for Mac2 (Edge / Reverse Proxy + TLS)
# Run this script AFTER you know all team IPs.
#
# Usage: ./setup_mac2.sh <Mac1_IP> <Mac3_IP>
# Example: ./setup_mac2.sh 10.42.31.100 10.42.31.150

set -euo pipefail

if [ $# -lt 2 ]; then
    echo "Usage: $0 <Mac1_IP> <Mac3_IP>"
    echo "Example: $0 10.42.31.100 10.42.31.150"
    exit 1
fi

MAC1_IP="$1"
MAC3_IP="$2"
MAC2_IP=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "UNKNOWN")
USERNAME=$(whoami)

echo "=== CN Project — Mac2 Setup ==="
echo "Mac1 IP (DNS + Backend B): $MAC1_IP"
echo "Mac2 IP (this machine):    $MAC2_IP"
echo "Mac3 IP (Backend A):       $MAC3_IP"
echo "Username:                  $USERNAME"
echo ""

# ---- Step 1: Create local project directory ----
echo "[1/6] Creating local project directory..."
mkdir -p ~/CN-Project/{tls,nginx,evidence}

# ---- Step 2: Copy TLS certs to local project dir ----
echo "[2/6] Setting up TLS certificates..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_TLS="$(dirname "$SCRIPT_DIR")/tls"

if [ -f "$REPO_TLS/app.teamX.test.crt" ] && [ -f "$REPO_TLS/app.teamX.test.key" ]; then
    cp "$REPO_TLS/app.teamX.test.crt" ~/CN-Project/tls/
    cp "$REPO_TLS/app.teamX.test.key" ~/CN-Project/tls/
    chmod 600 ~/CN-Project/tls/app.teamX.test.key
    echo "   ✓ Certificates copied to ~/CN-Project/tls/"
else
    echo "   ⚠ Certificate files not found. Run tls/generate_cert.sh first."
fi

# ---- Step 3: Generate nginx.conf with real IPs ----
echo "[3/6] Generating nginx.conf with real IPs..."
cat > ~/CN-Project/nginx/nginx.conf << NGINX_EOF
# nginx configuration for CN Project — LIVE DEPLOYMENT
# Generated by setup_mac2.sh on $(date)

worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log  /opt/homebrew/var/log/nginx/access.log;
    error_log   /opt/homebrew/var/log/nginx/error.log;

    # Upstream: round-robin load balancing across Backend A and Backend B
    upstream backend_pool {
        server ${MAC3_IP}:3001;   # Backend A (Mac3)
        server ${MAC1_IP}:3002;   # Backend B (Mac1)
    }

    # HTTPS server — TLS termination on port 8443
    server {
        listen 8443 ssl;
        server_name app.teamX.test;

        ssl_certificate     /Users/${USERNAME}/CN-Project/tls/app.teamX.test.crt;
        ssl_certificate_key /Users/${USERNAME}/CN-Project/tls/app.teamX.test.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            proxy_pass         http://backend_pool;
            proxy_http_version 1.1;
            proxy_set_header   Host \$host;
            proxy_set_header   X-Real-IP \$remote_addr;
            proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto https;
        }
    }
}
NGINX_EOF
echo "   ✓ nginx.conf generated at ~/CN-Project/nginx/nginx.conf"

# ---- Step 4: Back up and deploy nginx config ----
echo "[4/6] Deploying nginx configuration..."
NGINX_PREFIX=$(brew --prefix)/etc/nginx
if [ -f "$NGINX_PREFIX/nginx.conf" ]; then
    cp "$NGINX_PREFIX/nginx.conf" ~/CN-Project/nginx/nginx.conf.backup
    echo "   ✓ Original nginx.conf backed up"
fi
sudo cp ~/CN-Project/nginx/nginx.conf "$NGINX_PREFIX/nginx.conf"
echo "   ✓ New nginx.conf deployed"

# ---- Step 5: Syntax check ----
echo "[5/6] Running nginx syntax check..."
nginx -t 2>&1
echo "   ✓ Syntax check passed"

# ---- Step 6: Start/reload nginx ----
echo "[6/6] Starting nginx..."
brew services restart nginx 2>/dev/null || true
sleep 2

# Verify listening
echo ""
echo "=== Verification ==="
echo "Checking port 8443..."
lsof -nP -iTCP:8443 -sTCP:LISTEN 2>/dev/null || echo "   ⚠ nginx not yet listening on 8443 — check error log"

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Trust the certificate on this Mac:"
echo "     sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/CN-Project/tls/app.teamX.test.crt"
echo "  2. Send the .crt file to Mac1 and Mac3:"
echo "     scp ~/CN-Project/tls/app.teamX.test.crt <Mac1_user>@${MAC1_IP}:~/"
echo "     scp ~/CN-Project/tls/app.teamX.test.crt <Mac3_user>@${MAC3_IP}:~/"
echo "  3. Point this Mac to Mac1's DNS:"
echo "     sudo networksetup -setdnsservers 'Wi-Fi' ${MAC1_IP}"
echo "     dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
echo "  4. Test from this Mac:"
echo "     curl -i https://app.teamX.test:8443/api/status"
